plugins { id 'com.android.application' }
android {
 namespace 'com.example.floatingcandlescanner'; compileSdk 35
 defaultConfig { applicationId 'com.example.floatingcandlescanner.az'; minSdk 26; targetSdk 35; versionCode 54; versionName '14.9' }
 buildFeatures { buildConfig true }
 buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),'proguard-rules.pro' } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
